# -*- coding: utf-8 -*-
"""flask final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XypIDw0bxbOPgHiyNkT6kN6WBwGKVQOP
"""

# Step 1: Install Flask
!pip install flask

# Step 2: Create the Flask application
app_code = """
from flask import Flask

app = Flask(__name__)

@app.route('/')
def home():
    return "Hello, this is a simple Flask application!"

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
"""

with open('app.py', 'w') as f:
    f.write(app_code)

# Step 3: Use Colab's built-in public URL
from flask import Flask
from threading import Thread

app = Flask(__name__)

@app.route('/')
def home():
    return "Hello, this is a simple Flask application!"

def run():
    app.run(host='0.0.0.0', port=5000)

# Start a new thread to run the Flask app
t = Thread(target=run)
t.start()

# Use Colab's built-in public URL feature
from google.colab.output import eval_js
print(eval_js("google.colab.kernel.proxyPort(5000)"))

"""resume"""

app_code = """
from flask import Flask

app = Flask(__name__)

@app.route('/')
def home():
    resume = '''
    <html>
    <body>
        <h1>My Resume</h1>
        <p><strong>Name:</strong> Raja</p>
        <p><strong>Age:</strong> 22</p>
        <p><strong>Skills:</strong></p>
        <ul>
            <li>deep learning 1</li>
            <li>power bi 2</li>
            <li>machine learning 3</li>
        </ul>
        <p><strong>Email:</strong> abc@gmail.com</p>
    </body>
    </html>
    '''
    return resume

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8000)
"""

with open('app.py', 'w') as f:
    f.write(app_code)

from flask import Flask
from threading import Thread

app = Flask(__name__)

@app.route('/')
def home():
    resume = '''
    <html>
    <body>
        <h1>My Resume</h1>
        <p><strong>Name:</strong> Raja</p>
        <p><strong>Age:</strong> 22</p>
        <p><strong>Skills:</strong></p>
        <ul>
            <li>deep learning 1</li>
            <li>power bi 2</li>
            <li>machine learning 3</li>
        </ul>
        <p><strong>Email:</strong> abc@gmail.com</p>
    </body>
    </html>
    '''
    return resume

def run():
    app.run(host='0.0.0.0', port=8000)

# Start a new thread to run the Flask app
t = Thread(target=run)
t.start()

# Use Colab's built-in public URL feature
from google.colab.output import eval_js
print(eval_js("google.colab.kernel.proxyPort(8000)"))

